version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/data/database.sqlite
    volumes:
      - sqlite-data:/data
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  app-network:

volumes:
  sqlite-data: