version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/data/database.sqlite
      - RENDER=true
      - DEBUG=*
    volumes:
      - sqlite-data:/data:rw
    ports:
      - "5000:5000"
    restart: unless-stopped
    user: "node"
    healthcheck:
      test: ["CMD", "sqlite3", "/data/database.sqlite", "SELECT 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"

networks:
  app-network:

volumes:
  sqlite-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind