version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FrontendUrl=http://localhost:3000
      - DATABASE_URL=sqlite:/usr/src/app/database.sqlite
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start