version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FrontendUrl=http://your_vultr_ip:3000
      - DATABASE_URL=sqlite:/usr/src/app/database.sqlite
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge