version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/data/database.sqlite
      - RENDER=true
    volumes:
      - sqlite-data:/data:rw
    ports:
      - "5000:5000"
    restart: unless-stopped
    user: "node"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:

volumes:
  sqlite-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind