version: '3.3'

services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    external_links:
      - frontend_frontend_1
      - backend_backend_1
      - frontend
      - backend

networks:
  app-network:
    external: true