version: '3.3'

services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/letsencrypt
      - ./certificates-data:/var/lib/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'"
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./certificates-data:/var/lib/letsencrypt
    networks:
      - app-network
    command: certonly --webroot --webroot-path=/var/www/certbot -d twitx.duckdns.org

networks:
  app-network:
    external: true